### ISSUE TITLE
Adding more than 4 queues breaks the queue container layout

### ISSUE THREAD

**Issue by PHIMNADA024** [ParimaSA/Queue_Management#101]
## The problem
When more than 4 queues are added within the same type of queue, the queue container breaks and the additional queues become hidden, making it difficult to view all waiting queues. The layout does not accommodate the overflow of items properly.

## How to reproduce the problem
1. Add more than 4 queues in the same type of queue.
2. Observe that the queue container layout breaks and not all waiting queues are visible.

## Screenshot
![image](https://github.com/user-attachments/assets/e76bac4a-fb4e-4a59-ae8e-efdf20bc86ea)

**Comment by PHIMNADA024** [comment]
I also noticed that the print icon doesn't fully appear on the right side of the QR code queue. It would be helpful to fix this.

**Comment by Thanchida** [comment]
I have already fix it by adjust the size of the queue ticket and resize the component displaying entries in the queue to ensure all entries are fully visible. You can see the changes at https://queue-management-3owt1e0ef-parimas-projects.vercel.app/
