### ISSUE TITLE
business name does not stay in container when name is long

### ISSUE THREAD

**Issue by KhunakornP** [ParimaSA/Queue_Management#104]
## **Defect**
When creating a business that has a long name the name overflows out of the container

## **How To Reproduce**
1. Go to profile
2. Add a long business name such as `International Consortium for Advanced Technological Innovations and Sustainable Development Solutions LLC`

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

## ** Additional notes**
Ignore the queue name, I was testing emoji's

## **Screenshots**
![ui bug](https://github.com/user-attachments/assets/f2b6a1fb-2b3a-4747-963b-9e27160ed8fa)

**Comment by Thanchida** [comment]
I have already fix it by update the business name component to allow scrolling, preventing names from overflowing the container. You can see the changes at https://queue-management-kvnnpmzrx-parimas-projects.vercel.app/
