### ISSUE TITLE
Requirements Need Improvement

### ISSUE THREAD

**Issue by jbrucker** [ParimaSA/Queue_Management#7]
Requirements use imprecise language, which is a serious problem.
If you do not express a requirement clearly then it may be misinterpretted.

Here are some examples but not all.
* "customer can obtain a queue" - incorrect! A queue refers to the FIFO data structure, not an item (or reservation) in the queue.
* "see the places sorted by their location". What places?  Sorted how? By city name? Company name?  What is "place"?  I think of "place" as being a physical location, so this sentence doesn't make much sense.
* "their queue is almost up". Again you misuse the word "queue".  And what does "almost up" mean?  Too vague.
* "other customers to appoint the queue"  poor English.
* "including deleting customers who are late".  Is this a queue or an appointment scheduling app?  You describe it as a queue, which case a customer does **not** have a fixed appointment time, so he/she cannot be "late".  For a queue, its pretty standard that you automatically lose your opportunity to receive service if you fail to show up when your rservation reaches the top of the queue.

Next, I think the requirements are **incomplete**.

1. Can a business owner using this application create more than one queue?
2. What rules are used to identify customers who are allowed to reserve a spot in the queue?  
3. Can the queue owner limit the maximum number of reservations?  Is this value fixed or does it reduce during the day.  Looks like you did think about this aspect of queueing.

Nonfunctional Requirements are *trivial*.
- There must be more significant non-functional requirements than this.

You must **greatly improve** the requirements.  There are defects and missing requirement other than what are explicitly mentioned here.

If you fix only the things that I mention here, I will conclude that your team is lazy about requirements and give a low score for this.

**Comment by jbrucker** [comment]
Do not close this issue until the TA agrees.

**Comment by Thanchida** [comment]
**We decided to do Queue Management System**
### Edit
- Change wording from "obtain a queue" to "join a queue."
- Remove the location sorted feature.
- Change wording from "their queue is almost up" to "their turn in a queue is approaching."
- Clarify that "including deleting customers who are late" means the queue manager can delete a queue when a user does not arrive after being called by staff.

### Feature added
- Business owners can create multiple queues and can edit any queue at any time.
