### ISSUE TITLE
Queue or Appointment System?  Vision Needs Improvment

### ISSUE THREAD

**Issue by jbrucker** [ParimaSA/Queue_Management#8]
You wrote:
> ... at restaurants, hospitals, salons, government offices, and other venues.

are you thinking about a queue or an apppointment system?  

The examples you give are mixed.
- A salon or restaurant probably has an **appointment** system.  Customer makes a reservation for a particular date and time.
- Government Offices (at least the ones I've useed) are a first-come-first-served **queue** or many **queues**.
- Hospital has both **queue** for walk-in service, and **appointment** to see a specialist or for a specific service.  But the hospitals I've used **don't let patient make his own reservation** for either queue or service appointment.  The patient is not qualified enough to know what service he/she should receive.
- A restaurant could be either **queue** (like people waiting for a table at MK) or **appointment** (like at more high-end restaurants). 

The requirements are different.

The prospective users and their needs/goals are different.

The user stories are different.

So, what are you developing?   Queue or Reservation System?

Both your vision and requirements need to clarify this and be realistic about the scope of applications.

**Do not close** this issue until the TA agrees you have addressed it.

**Comment by yxzuz** [comment]
After some discussion, we decided to design a queue management system only and exclude outdated elements like location and appointment information. A few business examples that had nothing to do with the queue were eliminated from the vision. Customers are not allowed to add their own queues in any business. Only those in business roles are able to add a queue for their customers; for instance, hospital or restaurant employees will provide the tracking-code for customer to add to their queue to keep track of their queue entries.
